// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type Nav2DocumentDataSlicesSlice = Nav2ParentSlice;

/**
 * Content for Nav2 documents
 */
interface Nav2DocumentData {
	/**
	 * Slice Zone field in *Nav2*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav2.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<Nav2DocumentDataSlicesSlice>;
}

/**
 * Nav2 document from Prismic
 *
 * - **API ID**: `nav2`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Nav2Document<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<Nav2DocumentData>,
	'nav2',
	Lang
>;

type NavigationDocumentDataSlicesSlice = NavigationSlice;

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
	/**
	 * Slice Zone field in *Navigation*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<NavigationDocumentDataSlicesSlice>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<NavigationDocumentData>,
	'navigation',
	Lang
>;

type PageDocumentDataSlicesSlice =
	| TwoColumnTextSlice
	| OneColumnTextSlice
	| TwoColumnTextImageSlice
	| PageHeroSlice
	| FullScreenHeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

export type AllDocumentTypes = Nav2Document | NavigationDocument | PageDocument;

/**
 * Item in *CardList → Default → Primary → Card*
 */
export interface CardListSliceDefaultPrimaryCardItem {
	/**
	 * Title field in *CardList → Default → Primary → Card*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_list.default.primary.card[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * Description field in *CardList → Default → Primary → Card*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_list.default.primary.card[].description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Image field in *CardList → Default → Primary → Card*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_list.default.primary.card[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Name field in *CardList → Default → Primary → Card*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_list.default.primary.card[].name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;
}

/**
 * Primary content in *CardList → Default → Primary*
 */
export interface CardListSliceDefaultPrimary {
	/**
	 * Heading field in *CardList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_list.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * Card field in *CardList → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_list.default.primary.card[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	card: prismic.GroupField<Simplify<CardListSliceDefaultPrimaryCardItem>>;
}

/**
 * Default variation for CardList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardListSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<CardListSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *CardList*
 */
type CardListSliceVariation = CardListSliceDefault;

/**
 * CardList Shared Slice
 *
 * - **API ID**: `card_list`
 * - **Description**: CardList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardListSlice = prismic.SharedSlice<'card_list', CardListSliceVariation>;

/**
 * Primary content in *FullScreenHero → Default → Primary*
 */
export interface FullScreenHeroSliceDefaultPrimary {
	/**
	 * Heading field in *FullScreenHero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_hero.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	heading: prismic.KeyTextField;

	/**
	 * Subheading field in *FullScreenHero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_hero.default.primary.subheading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subheading: prismic.KeyTextField;

	/**
	 * Background Image field in *FullScreenHero → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_hero.default.primary.background_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	background_image: prismic.ImageField<never>;

	/**
	 * Button URL field in *FullScreenHero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_hero.default.primary.button_url
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for FullScreenHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullScreenHeroSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<FullScreenHeroSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *FullScreenHero*
 */
type FullScreenHeroSliceVariation = FullScreenHeroSliceDefault;

/**
 * FullScreenHero Shared Slice
 *
 * - **API ID**: `full_screen_hero`
 * - **Description**: FullScreenHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullScreenHeroSlice = prismic.SharedSlice<
	'full_screen_hero',
	FullScreenHeroSliceVariation
>;

/**
 * Primary content in *HeroText → Default → Primary*
 */
export interface HeroTextSliceDefaultPrimary {
	/**
	 * Title field in *HeroText → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_text.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * Subtitle field in *HeroText → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_text.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtitle: prismic.RichTextField;
}

/**
 * Default variation for HeroText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroTextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroTextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *HeroText*
 */
type HeroTextSliceVariation = HeroTextSliceDefault;

/**
 * HeroText Shared Slice
 *
 * - **API ID**: `hero_text`
 * - **Description**: HeroText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroTextSlice = prismic.SharedSlice<'hero_text', HeroTextSliceVariation>;

/**
 * Primary content in *Nav2Parent → Default → Primary*
 */
export interface Nav2ParentSliceDefaultPrimary {
	/**
	 * Label field in *Nav2Parent → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav2_parent.default.primary.label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * Link field in *Nav2Parent → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav2_parent.default.primary.link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.Repeatable<prismic.LinkField<string, string, unknown, prismic.FieldState, never>>;
}

/**
 * Default variation for Nav2Parent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Nav2ParentSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<Nav2ParentSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Nav2Parent*
 */
type Nav2ParentSliceVariation = Nav2ParentSliceDefault;

/**
 * Nav2Parent Shared Slice
 *
 * - **API ID**: `nav2_parent`
 * - **Description**: Nav2Parent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Nav2ParentSlice = prismic.SharedSlice<'nav2_parent', Nav2ParentSliceVariation>;

/**
 * Item in *Navigation → Default → Primary → Parent*
 */
export interface NavigationSliceDefaultPrimaryParentItem {
	/**
	 * Main Label field in *Navigation → Default → Primary → Parent*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.default.primary.parent[].main_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	main_label: prismic.KeyTextField;

	/**
	 * Submenu field in *Navigation → Default → Primary → Parent*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.default.primary.parent[].submenu
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	submenu: prismic.Repeatable<
		prismic.LinkField<string, string, unknown, prismic.FieldState, never>
	>;
}

/**
 * Primary content in *Navigation → Default → Primary*
 */
export interface NavigationSliceDefaultPrimary {
	/**
	 * Parent field in *Navigation → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.default.primary.parent[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	parent: prismic.GroupField<Simplify<NavigationSliceDefaultPrimaryParentItem>>;
}

/**
 * Default variation for Navigation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<NavigationSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Navigation*
 */
type NavigationSliceVariation = NavigationSliceDefault;

/**
 * Navigation Shared Slice
 *
 * - **API ID**: `navigation`
 * - **Description**: Navigation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationSlice = prismic.SharedSlice<'navigation', NavigationSliceVariation>;

/**
 * Primary content in *OneColumnText → Default → Primary*
 */
export interface OneColumnTextSliceDefaultPrimary {
	/**
	 * text field in *OneColumnText → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: one_column_text.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * centered field in *OneColumnText → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: one_column_text.default.primary.centered
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	centered: prismic.BooleanField;

	/**
	 * background color field in *OneColumnText → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: White
	 * - **API ID Path**: one_column_text.default.primary.background_color
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	background_color: prismic.SelectField<'White' | 'Green' | 'Cream' | 'Gray', 'filled'>;
}

/**
 * Default variation for OneColumnText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OneColumnTextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<OneColumnTextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *OneColumnText*
 */
type OneColumnTextSliceVariation = OneColumnTextSliceDefault;

/**
 * OneColumnText Shared Slice
 *
 * - **API ID**: `one_column_text`
 * - **Description**: OneColumnText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OneColumnTextSlice = prismic.SharedSlice<
	'one_column_text',
	OneColumnTextSliceVariation
>;

/**
 * Primary content in *PageHero → Default → Primary*
 */
export interface PageHeroSliceDefaultPrimary {
	/**
	 * Title field in *PageHero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_hero.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Intro field in *PageHero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_hero.default.primary.intro
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	intro: prismic.KeyTextField;
}

/**
 * Default variation for PageHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageHeroSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<PageHeroSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *PageHero*
 */
type PageHeroSliceVariation = PageHeroSliceDefault;

/**
 * PageHero Shared Slice
 *
 * - **API ID**: `page_hero`
 * - **Description**: PageHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageHeroSlice = prismic.SharedSlice<'page_hero', PageHeroSliceVariation>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
	/**
	 * Content field in *RichText → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Lorem ipsum...
	 * - **API ID Path**: rich_text.default.primary.content
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<RichTextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<'rich_text', RichTextSliceVariation>;

/**
 * Primary content in *TwoColumnText → Default → Primary*
 */
export interface TwoColumnTextSliceDefaultPrimary {
	/**
	 * ColumnOne field in *TwoColumnText → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: two_column_text.default.primary.columnone
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	columnone: prismic.RichTextField;

	/**
	 * ColumnTwo field in *TwoColumnText → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: two_column_text.default.primary.columntwo
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	columntwo: prismic.RichTextField;

	/**
	 * background color field in *TwoColumnText → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: White
	 * - **API ID Path**: two_column_text.default.primary.background_color
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	background_color: prismic.SelectField<'White' | 'Green' | 'Gray' | 'Cream', 'filled'>;
}

/**
 * Default variation for TwoColumnText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TwoColumnTextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TwoColumnTextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *TwoColumnText*
 */
type TwoColumnTextSliceVariation = TwoColumnTextSliceDefault;

/**
 * TwoColumnText Shared Slice
 *
 * - **API ID**: `two_column_text`
 * - **Description**: TwoColumnText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TwoColumnTextSlice = prismic.SharedSlice<
	'two_column_text',
	TwoColumnTextSliceVariation
>;

/**
 * Primary content in *TwoColumnTextImage → Default → Primary*
 */
export interface TwoColumnTextImageSliceDefaultPrimary {
	/**
	 * title field in *TwoColumnTextImage → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: two_column_text_image.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * text field in *TwoColumnTextImage → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: two_column_text_image.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Text Left, Image Right field in *TwoColumnTextImage → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: two_column_text_image.default.primary.text_left_image_right
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	text_left_image_right: prismic.BooleanField;

	/**
	 * image field in *TwoColumnTextImage → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: two_column_text_image.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for TwoColumnTextImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TwoColumnTextImageSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TwoColumnTextImageSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *TwoColumnTextImage*
 */
type TwoColumnTextImageSliceVariation = TwoColumnTextImageSliceDefault;

/**
 * TwoColumnTextImage Shared Slice
 *
 * - **API ID**: `two_column_text_image`
 * - **Description**: TwoColumnTextImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TwoColumnTextImageSlice = prismic.SharedSlice<
	'two_column_text_image',
	TwoColumnTextImageSliceVariation
>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			Nav2Document,
			Nav2DocumentData,
			Nav2DocumentDataSlicesSlice,
			NavigationDocument,
			NavigationDocumentData,
			NavigationDocumentDataSlicesSlice,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			AllDocumentTypes,
			CardListSlice,
			CardListSliceDefaultPrimaryCardItem,
			CardListSliceDefaultPrimary,
			CardListSliceVariation,
			CardListSliceDefault,
			FullScreenHeroSlice,
			FullScreenHeroSliceDefaultPrimary,
			FullScreenHeroSliceVariation,
			FullScreenHeroSliceDefault,
			HeroTextSlice,
			HeroTextSliceDefaultPrimary,
			HeroTextSliceVariation,
			HeroTextSliceDefault,
			Nav2ParentSlice,
			Nav2ParentSliceDefaultPrimary,
			Nav2ParentSliceVariation,
			Nav2ParentSliceDefault,
			NavigationSlice,
			NavigationSliceDefaultPrimaryParentItem,
			NavigationSliceDefaultPrimary,
			NavigationSliceVariation,
			NavigationSliceDefault,
			OneColumnTextSlice,
			OneColumnTextSliceDefaultPrimary,
			OneColumnTextSliceVariation,
			OneColumnTextSliceDefault,
			PageHeroSlice,
			PageHeroSliceDefaultPrimary,
			PageHeroSliceVariation,
			PageHeroSliceDefault,
			RichTextSlice,
			RichTextSliceDefaultPrimary,
			RichTextSliceVariation,
			RichTextSliceDefault,
			TwoColumnTextSlice,
			TwoColumnTextSliceDefaultPrimary,
			TwoColumnTextSliceVariation,
			TwoColumnTextSliceDefault,
			TwoColumnTextImageSlice,
			TwoColumnTextImageSliceDefaultPrimary,
			TwoColumnTextImageSliceVariation,
			TwoColumnTextImageSliceDefault
		};
	}
}
